import {
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  Copy,
  Database,
  Download,
  Eye,
  FileCode2,
  Filter,
  FolderOpen,
  History,
  Info,
  Key,
  KeyRound,
  Layers,
  Link2,
  List,
  ListTree,
  Loader2,
  Minus,
  Pencil,
  Play,
  Plug,
  PlugZap,
  Plus,
  RefreshCw,
  Save,
  Search,
  Settings,
  Square,
  Table2,
  Terminal,
  Trash2,
  Unplug,
  X,
  Zap,
  type LucideProps,
} from "lucide-react";

const ICONS = {
  alert: AlertTriangle,
  arrowDown: ArrowDown,
  arrowUp: ArrowUp,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  circle: Circle,
  copy: Copy,
  database: Database,
  download: Download,
  eye: Eye,
  fileCode: FileCode2,
  filter: Filter,
  folder: FolderOpen,
  history: History,
  info: Info,
  key: Key,
  keyRound: KeyRound,
  layers: Layers,
  link: Link2,
  list: List,
  tree: ListTree,
  loader: Loader2,
  minus: Minus,
  pencil: Pencil,
  play: Play,
  plug: Plug,
  plugZap: PlugZap,
  plus: Plus,
  refresh: RefreshCw,
  save: Save,
  search: Search,
  settings: Settings,
  square: Square,
  table: Table2,
  terminal: Terminal,
  trash: Trash2,
  unplug: Unplug,
  x: X,
  zap: Zap,
} as const;

export type IconName = keyof typeof ICONS;

export default function Icon({ name, size = 15, ...rest }: { name: IconName } & LucideProps) {
  const C = ICONS[name];
  return <C size={size} strokeWidth={1.9} aria-hidden {...rest} />;
}
